In [1]:
import requests
import pandas as pd 

BASE_URL = "https://openlibrary.org/search.json"

In [2]:
def search_openlibrary(query , limit = 100):

    params = {
        "q": query ,
        "limit":limit
    }

    headers = {
        "User-Agent" : "Bookverse/0.1"
    }

    response = requests.get(
        BASE_URL,
        params = params,
        headers = headers , 
        timeout = 30
    )

    response.raise_for_status()

    return response.json()

In [3]:
fantasy = search_openlibrary("fantasy", 100)

len(fantasy["docs"])

100

In [4]:
horror = search_openlibrary("horror" , 100)

len(horror["docs"])

100

In [5]:
hindi = search_openlibrary("Hindi novels" , 100)

len(hindi["docs"])

100

In [6]:
manga = search_openlibrary("manga" , 100)
len(manga["docs"])

100

In [19]:
fantasy_df = pd.DataFrame(fantasy["docs"])
fantasy_df.shape

(100, 22)

In [9]:
fantasy_df.columns.tolist()

['author_key',
 'author_name',
 'cover_edition_key',
 'cover_i',
 'ebook_access',
 'edition_count',
 'first_publish_year',
 'has_fulltext',
 'ia',
 'ia_collection',
 'key',
 'language',
 'public_scan_b',
 'title',
 'lending_edition_s',
 'lending_identifier_s',
 'series_key',
 'series_name',
 'series_position',
 'subtitle',
 'id_standard_ebooks',
 'id_project_gutenberg']

In [11]:
fantasy_df[["title" , "author_name" , "language"]].head(20)

,title,author_name,language
0,Fantasy Girl,[Carole Mortimer],"[eng, und]"
1,Her Christmas Fantasy,[Penny Jordan],[eng]
2,Fantasy,[Emma Darcy],[eng]
3,My Secret Garden,[Nancy Friday],"[hrv, dut, fre, chi, eng]"
4,Fantasy in death,"[Nora Roberts, Susan Ericksen]","[fre, eng]"
5,Powerless,[Lauren Roberts],"[spa, eng, por]"
6,The Kingdom of Fantasy,"[Elisabetta Dami, David Nel·lo, Larry Keys, Ti...","[eng, spa, fre, dut]"
7,Forbidden Flowers,[Nancy Friday],[eng]
8,Fantasy Lover,[Sherrilyn Kenyon],[eng]
9,Lilith,[George MacDonald],"[fre, ger, eng, ita]"
10,Men in Love: Men's Sexual Fantasies,[Nancy Friday],"[eng, fre, und]"
11,Fantasy for Two,[Penny Jordan],[eng]
12,The ghost,[Arnold Bennett],[eng]
13,Fantasy encyclopedia,"[Judy Allen, Richard Hook, Jonathan Stroud, Jo...",[eng]
14,Restoree,[Anne McCaffrey],"[fre, ger, eng]"
15,Belladonna,[Adalyn Grace],"[ger, eng]"
16,Dragonsong,[Anne McCaffrey],"[fre, eng, por]"
17,Flight to fantasy,[Margaret Malcolm],[eng]
18,Phantasma,[Kaylie Smith],"[dut, eng, ita]"
19,Castle Roogna,[Piers Anthony],[eng]

In [13]:
manga_df = pd.DataFrame(manga["docs"])

manga_df[["title","author_name","language"]].head(20)

,title,author_name,language
0,Maximum Ride. The Manga 1,[NaRae Lee],[eng]
1,Soulless,[Gail Carriger],[eng]
2,How to Draw Manga,[Hikaru Hayashi],[eng]
3,"Maximum Ride, The Manga 3","[NaRae Lee, James Patterson]",[eng]
4,How to Draw Manga,"[Manga University, Ryo Katagiri, Hiroyuki Seng...",[eng]
5,The Lost Warrior,"[Erin Hunter, Dan Jolley]","[pol, eng]"
6,Manga Classics,"[William Shakespeare, Crystal S. Chan, Julien ...",[eng]
7,Manga! Manga!,[Frederik L. Schodt],[eng]
8,Erotic Manga,[Ikari Studio],[eng]
9,The Life-Changing Magic of Tidying Up,"[Marie Kondo, Yuko Uramoto, Marie Kondo]","[por, jpn, eng, spa]"
10,How to Draw Manga Bodies & Anatomy,[Society for the Study of Manga Techniques],[eng]
11,The Manga Guide to Databases,"[Mana Takahashi, Mana Takahashi; ShoÌ„ko Azuma...","[ita, eng]"
12,Art of drawing manga,"[Sergi Cámara, Sergi Camara, Vanessa Duran]",[eng]
13,Hokusai manga,[Hokusai Katsushika],[jpn]
14,How to Draw Manga,[Katsuya Yamakami],[eng]
15,"Maximum Ride. The Manga, Vol. 4",[NaRae Lee],[eng]
16,How To Draw Manga: Ultimate Manga Lessons Volu...,[Go Office],[eng]
17,Berserk,[Cartoch Arts],[eng]
18,The Manga Guide to Statistics,[Shin Takahashi],"[ita, eng]"
19,How to draw more Manga,[Katy Coope],[eng]

In [18]:
horror_df = pd.DataFrame(horror["docs"])
horror_df.columns.tolist()

['author_key',
 'author_name',
 'cover_edition_key',
 'cover_i',
 'ebook_access',
 'edition_count',
 'first_publish_year',
 'has_fulltext',
 'ia',
 'ia_collection',
 'key',
 'language',
 'lending_edition_s',
 'lending_identifier_s',
 'public_scan_b',
 'title',
 'subtitle',
 'id_standard_ebooks',
 'id_project_gutenberg',
 'series_key',
 'series_name',
 'series_position']

In [17]:
horror_df[["title" , "author_name","language"]].head(20)

,title,author_name,language
0,The Amityville Horror,[Jay Anson],"[eng, und, spa]"
1,Uzumaki,[Junji Itō],"[por, eng, spa]"
2,The Dunwich Horror,[H.P. Lovecraft],"[eng, spa]"
3,The First Horror,[Robert Lawrence Stine],[eng]
4,50 great horror stories,[John Canning],[eng]
5,The troop,[Nick Cutter],[eng]
6,The Lifeguard,[Richie Tankersley Cusick],[eng]
7,Thirteen,"[T. Pines, D. E. Athkins, A. Bates, Jay Bennet...",[eng]
8,Teacher's Pet,[Richie Tankersley Cusick],"[spa, eng]"
9,Dunwich Horror,[H.P. Lovecraft],"[ger, eng]"
10,Southern Horrors,"[Ida B. Wells-Barnett, I. Garland Penn, T. Tho...",[eng]
11,99 Fear Street - The House of Evil - The Secon...,[Robert Lawrence Stine],[eng]
12,99 Fear Street,[Robert Lawrence Stine],[eng]
13,Dark Forces,"[Kirby McCauley, Dennis Etchison, Isaac Bashev...",[eng]
14,#Horror,[Siddhartha Sarma],[eng]
15,"Book of Horrors (Nightmare Hall, No 16)",[Diane Hoh],[eng]
16,Danse Macabre,[Stephen King],"[jpn, ger, ita, und, eng, rus, pol, hun]"
17,Dracula,[Bram Stoker],"[gle, por, cat, tur, ger, eng, alb, chi, glg, ..."
18,The Conspiracy Against the Human Race,[Thomas Ligotti],[eng]
19,Goosebumps Hall of Horrors - Claws!,[Robert Lawrence Stine],[eng]

In [21]:
hindi_df = pd.DataFrame(hindi["docs"])
hindi_df.columns.tolist()

['author_key',
 'author_name',
 'cover_edition_key',
 'cover_i',
 'ebook_access',
 'edition_count',
 'first_publish_year',
 'has_fulltext',
 'ia',
 'ia_collection',
 'key',
 'language',
 'lending_edition_s',
 'lending_identifier_s',
 'public_scan_b',
 'title',
 'subtitle',
 'id_standard_ebooks',
 'id_project_gutenberg',
 'id_librivox',
 'series_key',
 'series_name',
 'series_position',
 'id_wikisource']

In [22]:
hindi_df[["title","author_name","language"]].head(20)

,title,author_name,language
0,Godāna,[Munshi Premchand],"[hin, guj, eng]"
1,A Window Lived in a Wall ; Sahitya Akademi Awa...,[Vinod Kumar Shukla],[eng]
2,Rameshwara Hindi Novel,NaN,NaN
3,"Hindi novels, 1850-1950",NaN,[eng]
4,Romantic feminism in Hindi novels written by w...,[Indu Prakash Pandey],[eng]
5,Pratishodh,[akhil chandra],[hin]
6,Ret Smadhi,[Geetanjali Shree],[eng]
7,Punarvas,[K .N. Sahay],NaN
8,Between Love and Freedom,[Nikhil Govind],[eng]
9,Regionalism in Hindi novels,[Indu Prakash Pandey],[eng]
10,Khubsurat-- Pakhandi,[K .N. Sahay],NaN
11,Hindī upanyāsakāra kośa =,[Santosha Goyala],[hin]
12,Postmodern Traces and Recent Hindi Novels,[Veronica Ghirardi],[eng]
13,TAFTEESH-(Hindi version),[Mitter Sain Meet],[hin]
14,Mera Tisra Beta,[K .N. Sahay],NaN
15,Crome yellow,[Aldous Huxley],"[eng, fre, rus, spa]"
16,Girirāj Kiśor's Yātrāeṁ,[Th Damsteegt],[eng]
17,The Face behind seven veils,[Amritlal Nagar],[eng]
18,Ghar Dar Log (Hindi Novel),[Jitendra Sharma],[hin]
19,Sociology of Indian literature,[Sulocanā Rāṅgeya Rāghava],[eng]

In [24]:
print(fantasy_df.shape)
print(horror_df.shape)
print(hindi_df.shape)
print(manga_df.shape)

(100, 22)
(100, 22)
(100, 24)
(100, 17)